version: '2'
services:
  apache:
    build:
      context: docker/apache
      dockerfile: Dockerfile
    environment:
      ENV: dev
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_NAME: smart-coin
      DATABASE_PASSWORD: 
    volumes:
      - .:/var/www/project
    ports:
      - "80:80"
    links:
      - mailcatcher:smtp
      - "mysql:mysql"
  # node:
  #   build:
  #     context: .
  #     dockerfile: docker/node/Dockerfile
  #   restart: always
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: bash -c "ln -sf /node_modules node_modules && /bin/ping localhost"
  #   ports:
  #     - "8080:8080"

  mysql:
    image: mysql:5.7.25
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: smart-coin
    volumes:
      - mysql5:/var/lib/mysql
    ports:
      - "3306:3306"
 
  #uncomment to test emails locally by visiting http://localhost:1080
  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    ports:
      - "1080:1080"
volumes:
  mysql5:
      external: false
