kind: Service
apiVersion: v1
metadata:
  #Service name
  name: smart-coin-svc
spec:
  selector:
    app: brandwebs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer