apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcoin-2
  labels:
    #Project ID
    app: brandwebs
spec:
  #Run two instances of our application
  replicas: 1
  selector:
      matchLabels:
        app: brandwebs
  template:
    metadata:
      labels:
        app: brandwebs
    spec:
      #Container details
      containers:
        - name: smart-coin-2
          image: gcr.io/brandwebs/smart-coin:latest
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 800
          envFrom:
          - configMapRef:
              name: app-config