apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DEBUG: "false"
  TEST_MODE: "false"
  SERVER_ROOT: "/var/www/project/webroot"
  TIMEZONE: "Africa/Johannesburg"
  DATABASE_HOST: "localhost"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "vKii2mHeyH24P6hq"
  MYSQL_DATABASE: "outdoor_warehouse"